#!/usr/bin/env python3.7

from argparse import ArgumentParser
from mongoengine import connect

from devel_ball.create_pandas import create_raw_dataframe

if __name__ == '__main__':

    parser = ArgumentParser()
    parser.add_argument('--years', default=['2018-19'], nargs='*',
                        help='Years to acquire player data for. Please use the'
                             ' format xxxx-xx, e.g. 2019-20.'
                       )
    parser.add_argument('--name', default=None, help='Name for the pickle')
    args = parser.parse_args()

    # Connect to the local mongo client and devel_ball database
    mongo_client = connect('devel_ball')
    create_raw_dataframe(args.years, args.name)
