#!/usr/bin/env python3.7

import pandas as pd
from argparse import ArgumentParser
from joblib import dump, load

from devel_ball.analysis import get_model


if __name__ == '__main__':

    parser = ArgumentParser()
    parser.add_argument('--years', default=['2018-19'], nargs='*',
                        help='Years to acquire player data for. Please use the'
                             ' format xxxx-xx, e.g. 2019-20.'
                       )
    parser.add_argument('--name', default='model.p', help='Name for the model')
    args = parser.parse_args()

    # TODO (allow for internal combination of multiple pandas files for each year)
    data = pd.read_pickle('~/devel_ball/data/pandas/{}.p'.format(args.years[0]))

    model = get_model(data)
    dump(model, args.name)
